<!-- 这里面可以引用一些公共js和css -->
 <link href="/assets/lib/css/animate.css" rel="stylesheet"/>
<link href="/assets/css/common.css" rel="stylesheet"/>
<script src="/assets/lib/js/jquery-3.3.1.min.js"></script>
<script src="/assets/lib/js/fastclick.js"></script>
<link rel="stylesheet" href="/assets/lib/jquery.bxslider/css/jquery.bxslider.css">
<script src="/assets/lib/jquery.bxslider/js/jquery.bxslider.js"></script>